# 12.9
nohup bash scripts/generate_pretrain_data.sh ./xprophetnet_models ../datasets/small_NTG 2 huggingface_prophetnet_ntg_ckpt_4.pt 1 generate_data &> logs/try_generate.out &
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_generate_data && . /tmp/env_generate_data/bin/activate && python -m pip install -r requirements.txt && bash scripts/generate_pretrain_data.sh [#input-previous-model-path] [#input-training-data-path] 24 huggingface_prophetnet_sampled_aug_filter.pt 1 generate_data"
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_full_generate_data && . /tmp/env_full_generate_data/bin/activate && python -m pip install -r requirements.txt && bash scripts/generate_pretrain_data.sh [#input-previous-model-path] [#input-training-data-path] 24 huggingface_prophetnet_sampled_aug_filter.pt 1 generate_data"

export CUDA_VISIBLE_DEVICES=0,1
python pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path examples/models/try_mbart_model --use_official_pretrained --pretrained_model=../ckpt/mbart-large-cc25 --tokenizer_name_or_path ../ckpt/mbart-large-cc25 --langs hi,en,vi --mono_src examples/data/train.hi,examples/data/train.en,examples/data/train.vi --shard_files
nohup python -u pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path examples/models/try_mbart_model --use_official_pretrained --pretrained_model=../ckpt/mbart-large-cc25 --tokenizer_name_or_path ../ckpt/mbart-large-cc25 --langs en,fr --mono_src ../datasets/small_NTG/xglue.ntg.en.src.train,../datasets/small_NTG/xglue.ntg.fr.src.train --shard_files --lr=1e-5 &> logs/try_pretrain.out &
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_pretrain_en && . /tmp/env_pretrain_en/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path=res/pretrain_en/12.9 --use_official_pretrained --pretrained_model=[#input-previous-model-path] --tokenizer_name_or_path=[#input-previous-model-path] --langs=en --mono_src=[#input-training-data-path]/xglue.ntg.en.src.train --shard_files --lr=1e-5 --batch_size=1024 --no_reload_optimizer_ctr_and_scheduler"

