# 12.9
export CUDA_VISIBLE_DEVICES=0,1
python pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path examples/models/try_mbart_model --use_official_pretrained --pretrained_model=../ckpt/mbart-large-cc25 --tokenizer_name_or_path ../ckpt/mbart-large-cc25 --langs hi,en,vi --mono_src examples/data/train.hi,examples/data/train.en,examples/data/train.vi --shard_files
nohup python -u pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path examples/models/try_mbart_model --use_official_pretrained --pretrained_model=../ckpt/mbart-large-cc25 --tokenizer_name_or_path ../ckpt/mbart-large-cc25 --langs en,fr --mono_src ../datasets/small_NTG/xglue.ntg.en.src.train,../datasets/small_NTG/xglue.ntg.fr.src.train --shard_files --lr=1e-5 &> logs/try_pretrain.out &
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_pretrain_en && . /tmp/env_pretrain_en/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u pretrain_mbart.py -n 1  -nr 0 -g 2  --model_path=res/pretrain_en/12.9 --use_official_pretrained --pretrained_model=[#input-previous-model-path] --tokenizer_name_or_path=[#input-previous-model-path] --langs=en --mono_src=[#input-training-data-path]/xglue.ntg.en.src.train --shard_files --lr=1e-5 --batch_size=1024 --no_reload_optimizer_ctr_and_scheduler"

nohup python -u generate_mbart.py -n 1  -nr 0 -g 1 --model_path examples/models/try_generate --use_official_pretrained --pretrained_model=../ckpt/mbart-large-cc25 --tokenizer_name_or_path=../ckpt/mbart-large-cc25 --dev_slang en --dev_tlang en --dev_src ../datasets/small_NTG/xglue.ntg.en.src.train --dev_tgt ../datasets/small_NTG/xglue.ntg.en.src.train --shard_files  &> logs/try_generate.out &

# 12.15
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_generate_en && . /tmp/env_generate_en/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u generate_mbart.py -n 1  -nr 0 -g 1  --model_path=res/generate_en/12.14 --use_official_pretrained --pretrained_model=[#input-previous-model-path]/en --tokenizer_name_or_path=[#input-previous-model-path]/en --dev_slang=en --dev_tlang=en --dev_src=[#input-training-data-path]/xglue.ntg.en.src.train --dev_tgt=[#input-training-data-path]/xglue.ntg.en.src.train --shard_files --no_reload_optimizer_ctr_and_scheduler"

"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_pretrain_en && . /tmp/env_pretrain_en/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u pretrain_mbart.py -n 1  -nr 0 -g 1  --model_path=res/pretrain_en/12.14 --use_official_pretrained --pretrained_model=[#input-previous-model-path] --tokenizer_name_or_path=[#input-previous-model-path] --langs=en --mono_src=[#input-training-data-path]/xglue.ntg.en.src.train --shard_files --lr=1e-5 --batch_size=1024 --no_reload_optimizer_ctr_and_scheduler"

# 12.16
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_generate_en && . /tmp/env_generate_en/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u generate_mbart.py -n 1  -nr 0 -g 1  --model_path=res/generate_en/12.16 --use_official_pretrained --pretrained_model=[#input-previous-model-path]/en --tokenizer_name_or_path=[#input-previous-model-path]/en --dev_slang=en --dev_tlang=en --dev_src=[#input-training-data-path]/xglue.ntg.en.src.train --dev_tgt=[#input-training-data-path]/xglue.ntg.en.src.train --shard_files --no_reload_optimizer_ctr_and_scheduler"

# 12.19
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_pretrain_de && . /tmp/env_pretrain_de/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u pretrain_mbart.py -n 1  -nr 0 -g 1  --model_path=res/pretrain_de/12.19 --use_official_pretrained --pretrained_model=[#input-previous-model-path] --tokenizer_name_or_path=[#input-previous-model-path] --langs=en,de --mono_src=[#input-training-data-path]/xglue.ntg.en.src.train,[#input-training-data-path]/xglue.ntg.de.src.train --shard_files --lr=1e-5 --batch_size=1024 --no_reload_optimizer_ctr_and_scheduler"
"python -m pip install virtualenv --user && python -m virtualenv /tmp/env_pretrain_@@lang@@ && . /tmp/env_pretrain_@@lang@@/bin/activate && python -m pip install -r requirements.txt && cd transformers && python setup.py install && cd .. && python -u pretrain_mbart.py -n 1  -nr 0 -g 1  --model_path=res/pretrain_@@lang@@/12.19 --use_official_pretrained --pretrained_model=[#input-previous-model-path] --tokenizer_name_or_path=[#input-previous-model-path] --langs=en,@@lang@@ --mono_src=[#input-training-data-path]/xglue.ntg.en.src.train,[#input-training-data-path]/xglue.ntg.@@lang@@.src.train --shard_files --lr=1e-5 --batch_size=1024 --no_reload_optimizer_ctr_and_scheduler"
